baseURL: 'https://website22emma.netlify.app/'
languageCode: en-us
title: Dopest website out there 
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  name: I am Emma Zurstrassen
  description: Emma's website
  custom_css: []
  custom_js: []
  favicon: favicon.ico
  image: ''
  error404:
    heading: Page couldn't be found
    text: 'Please visit [this page](/)'
  navigation:
    title: Goodmorning 
    subtitle: internet people
    menu: Menu
    links:
      - name: Homepage
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
  banner:
    title: "Hi I'm Emma"
    subtitle: |-
      Who is she ? What does she do ? What does she like ? 
    buttonText: answer all your questions 
  tiles:
    enable: true
    showcase:
      - title: Who's Emma ? 
        subtitle: A bit about me 
        image: cover_website.JPG
        url: blogs/emma
      - title: CV
        subtitle: A bit more formal
        image: pic02.jpg
        url: blogs/cv
      - title: Project 1 
        subtitle: Lorem Etiam Nullam
        image: pic03.jpg
        url: blogs/project1
      - title: Project 2
        subtitle: Nisl Sed Aliquam
        image: pic04.jpg
        url: blogs/project2
      - title: Consequat
        subtitle: Ipsum Dolor Sit Amet
        image: pic05.jpg
        url: blogs/ipsum
      - title: Etiam
        subtitle: Feugiat Amet Tempus
        image: pic06.jpg
        url: blogs/ipsum
  blog: {}
  two:
    enable: true
    title: Dear website visitor 
    subtitle: |-
      I hope you were able to get to know me through this website. Feel free to reach out if you have any questions, want to know more about me or just want to hang out for a coffee. 
      Always happy to meet new people and hear fun stories. 
    buttonText: Discover my work 
    url: blogs
  contact:
    enable: true
    buttonSend: Send message
    buttonClear: Clear
    email:
      - title: Email
        email: emmazurs@gmail.com
    phone:
      - title: text me 
        phone: +32 479 47 63 65
    address:
      - title: write me 
        street: 3 Chilworth Mews
        city: 'London'
        country: UK
  footer:
    enable: true
    copyright: Emma Zurstrassen
    social:
      - icon: fa-twitter
        url: 'https://twitter.com/EmmaZurstrassen'
        label: Twitter
      - icon: fa-facebook
        url: 'https://www.facebook.com/emma.zurstrassen/'
        label: Facebook
      - icon: fa-instagram
        url: 'https://www.instagram.com/emmazrst/'
        label: Instagram
      - icon: fa-github
        url: 'https://github.com/emmazrst'
        label: GitHub
      - icon: fa-linkedin
        url: 'https://www.linkedin.com/in/emmazurs/'
        label: LinkedIn
    quicklinks:
      - text: 'Design: '
        url: 'https://www.html5up.net'
        alt: HTML5 UP
